title: Tristan Davey
author: Tristan Davey
author_email: tristan@tristandavey.com

plugins:
  - jekyll-paginate
  - jekyll-assets

assets:
  sources:
    - _assets/css
    - _assets/images
    - _assets/fonts
    - _assets/js
  prefix: "/assets"

excerpt_separator: <!-- excerpt-end -->
permalink: /blog/:categories/:title/

paginate_path: "/blog/page:num/"
paginate: 5

exclude: [README.markdown, package.json, npm-debug.log, Gemfile, Gemfile.lock, gulpfile.js, node_modules]
